format = """
$character\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang"""
add_newline = false

[character]
success_symbol = "[âžœ](bold green)"
error_symbol = "[âžœ](bold red)"

[directory]
truncation_length = 1
read_only = " ðŸ”’"
style = "cyan"

[git_branch]
# format = '[\[îœ‰ [$branch](red)\]](blue) '
format = '[\[[$branch](red)\]](blue) '

[git_status]
style = "purple"

[python]
format = "[îœ¼ $virtualenv ]($style) "
style = "yellow"

[nodejs]
symbol = "îœ˜ "
format = "[$symbol]($style) "
style = "cyan"

[rust]
symbol = "îž¨ "
format = "[$symbol]($style) "
style = "red"

[golang]
symbol = "î˜§ "
format = "[$symbol]($style) "
style = "blue"

